### ISSUE TITLE
Value cannot be null

### ISSUE THREAD

**Issue by timlaw55** [FirelyTeam/spark#170]
When running the "Spark" project from either spark-r4-master or spark-r4-develop and then try to access a patient i.e. http://localhost/patient/001 a null reference exception is thrown in src\Spark\App_Start\UnityControllerFactory.cs line 27.  controllerType is null but should not be.  Not sure how to resolve this problem.

**Comment by brianpos** [comment]
Note that the route is case sensitive.
/Patient/001

**Comment by kennethmyhra** [comment]
As Brian says, route is case sensitive. In addition should be prefixed with /fhir, full relative path should look like this /fhir/Patient/001

**Comment by timlaw55** [comment]
Thank you for your reply.  I will pay closer attention to my casing.  The real problem turned out to be a database connection problem.  Some better reporting when the database can't be reached may be in order.  A null reference exception in the unity controller is thrown which was not very helpful in finding the db problem.

**Comment by kennethmyhra** [comment]
I just did some tests on this
* if there is a database connection problem an OperationOutcome is thrown containing the error for the connection problem.
* If I remove the MONGOLAB_URI completely Spark throws an ArgumentException on startup of the application because a required configuration variable is missing, this could probably be handled a bit smoother.
* If the casing is off an OperationOutcome is returned suggesting the proper casing.
* If I somehow try to access a route that the does not exists on the server like http://spark.kufu.no/Patient/example you will get the ArgumentNullException that you initially posted, as with the missing required configuration variable this could probably be handled a bit smoother.

I will put the issue into the backlog to try and smooth out the errors a bit

**Comment by kennethmyhra** [comment]
Latest version of Spark (v1.3) renders OperationOutcome to the web browser, considering this as solved
