### ISSUE TITLE
POSTing to a id with a dot gives a 404

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/spark#19]
E.g. POST http://spark.furore.com/fhir/Patient/12.345....

I think the WebApi framework thinks you are trying to reach the "12" resource, with extension "345"

**Comment by CorinaCiocanea** [comment]
After a bit of investigation, I'm not sure we should do something about this.

Apparently this happens because IIS assumes we are looking for a file. It sees a "." in the url and assumes it is a file name with an extension. Adding an extra **"/"** as in  **POST http://spark.furore.com/fhir/Patient/12.345..../** would solve the problem (http://weblogs.asp.net/owscott/handing-mvc-paths-with-dots-in-the-path )

I've found several solutions/workarounds for fixing it, but I'm not sure we want to implement any of them.

One would be to add this in web.config
```
<system.webserver>
    <modules runAllManagedModulesForAllRequests="true">
```
But this implies performance costs, so it's not something we want.

Another solution would be to add an IIS URL Rewrite to add an extra / to all requests. Do we want this for all requests? Are we able to distinguish which urls should re-written?

What do you think?

**Comment by mharthoorn** [comment]
We'll postpone resolving this until after moving to ASP.NET core.

**Comment by kennethmyhra** [comment]
Fixed as described here: https://stackoverflow.com/a/12151501/1597945
