### ISSUE TITLE
Server return 406

### ISSUE THREAD

**Issue by one0410** [FirelyTeam/spark#368]
**Describe the bug**
When I simply upgrade from 1.5.3-r4 to 1.5.4-r4. I got a 406 response, when I try to get data from API.

**To Reproduce**
![image](https://user-images.githubusercontent.com/11656628/114662193-db65c800-9d2a-11eb-9558-e6ea58a1af33.png)
Using built-in swagger.
Server return 406.

![image](https://user-images.githubusercontent.com/11656628/114662305-07814900-9d2b-11eb-9dd3-da74ad6d6c99.png)

**Comment by kennethmyhra** [comment]
You will need to select application/json in the Media Type dropdown below or one of the other supported FHIR formats like: application/fhir+json, application/xml, application/fhir+xml. I'm looking at a way to restrict the Media Types in the Swagger Document.

The reason for this happening in 1.5.4 R4 is because this issue was implemented: https://github.com/FirelyTeam/spark/issues/323

![image](https://user-images.githubusercontent.com/248795/114696098-98045d00-9d1c-11eb-8317-457e75fa563b.png)
