### ISSUE TITLE
Duplicate search indexes being created under rapid updates

### ISSUE THREAD

**Issue by kennethmyhra** [FirelyTeam/spark#399]
**Describe the bug**
Under rapid updates we occasionally see duplicate searchindexes being created

**To Reproduce**
Execute rapid updates

**Expected behavior**
To not end up with duplicate search indexes

**Additional context**
Our updates can come in very rapidly sometimes which is not ideal but not something we can easily fix at the moment. My suspicion on the issue is as follows: As the updates come in, in a perfect world the code should execute like this:

update 1 Remove()
update 1 Insert()
update 2 Remove()
update 2 Insert()

In reality, I think there are instances where this happens (and this might be unique to our infrastructure / setup):

update 1 Remove()
update 2 Remove()
update 1 Insert()
update 2 Insert()

https://github.com/FirelyTeam/spark/blob/76c6499806e9986ac0d12309d7d7491224049e89/src/Spark.Mongo/Search/Infrastructure/MongoIndexStore.cs#L59

**Comment by kennethmyhra** [comment]
Also see #398 

For your information @phrederick

**Comment by phrederick** [comment]
So the question from @kennethmyhra was whether I can test out a solution using Update instead of Remove + Insert.
I've done that our own solution which is based on a much older version of Spark and it seems to work.

To replicate the issue, what I did was create a basic script in Postman that would spam updates to 'Schedule' resources until we had two 'searchindex' documents - this typically would happen within 5 minutes or so of the spam script running, but sometimes a little longer. I'm not sure how I would go about setting up such a test framework on your branch as I don't think I could easily bring our code up-to-date, but I've shared my changes, and what I think should be the equivalent changes in this solution below if that helps. I am also happy to help with attempting to replicate it in your solution if someone can give me some instructions for setting up a test app.

```csharp
// Our implementation
public void Save(BsonDocument document)
{
	try
	{
		string keyvalue = document.GetValue(InternalField.ID).ToString();
		IMongoQuery query = MongoDB.Driver.Builders.Query.EQ(InternalField.ID, keyvalue);
                // todo: should use Update: collection.Update();
                //_collection.Remove(query);
                //_collection.Insert(document);
		IMongoUpdate update = MongoDB.Driver.Builders.Update.Replace(document);
		var flags = UpdateFlags.Upsert;
		_collection.Update(query, update, flags);
	}
	catch (Exception exception)
	{
		throw exception;
	}
}
```

```csharp
// Your implementation
public async Task SaveAsync(BsonDocument document)
{
	string keyvalue = document.GetValue(InternalField.ID).ToString();
	var query = Builders<BsonDocument>.Filter.Eq(InternalField.ID, keyvalue);

        //await Collection.DeleteManyAsync(query).ConfigureAwait(false);
        //await Collection.InsertOneAsync(document).ConfigureAwait(false);
	var options = new UpdateOptions { IsUpsert = true };
	await Collection.UpdateOneAsync(query, document, options).ConfigureAwait(false);
}
```

**Comment by kennethmyhra** [comment]
Thanks for verifying this @phrederick!
