### ISSUE TITLE
Security Issue: Cross site scripting attack 

### ISSUE THREAD

**Issue by kmmithun** [FirelyTeam/spark#59]
Hi,

I am using DSTU2 May 2015 version. Recently identified two of the security issue with respect to encoding.

Cross site scripting attack is possible with current encoding technique used in the framework. I tried to restrict XSS using encoderType="System.Web.Security.AntiXss.AntiXssEncoder" in web.config at application level but still the below issues persist.

Issue 1  : Reflected XSS at almost all input fields
Issue 2: Stored XSS at string fields.

Have any of you encountered this issue or the fix for same has been done? Please let me know.

**Comment by ewoutkramer** [comment]
Hi kmmithun,

Can you clarify a bit more which issues you are having?  E.g. what is an "input field"?  Since Spark is a RESTful service, do you mean the contents of an element in a resource?  

The Serializer will correctly escape tags, like so:

<Patient xmlns="http://hl7.org/fhir"><name><family value="&lt;script language='javascript'&gt;&lt;/script&gt;" /></name></Patient>

Can you point out where things need to be improved?

**Comment by kennethmyhra** [comment]
Closing this based on lack of response, escaping is handled in the serializers.
